# Generated by using rustinr::rustrize() -> do not edit by hand


bolt_begin_internal = function(uri,username,password){ .Call('RNeo4j_bolt_begin_internal',PACKAGE = 'RNeo4j', uri,username,password)}

bolt_query_internal = function(graph,query,params,as_data_frame){ .Call('RNeo4j_bolt_query_internal',PACKAGE = 'RNeo4j', graph,query,params,as_data_frame)}
